/*
 * EnvSensorConfig.hpp
 *
 *  Created on: Apr 23, 2023
 *      Author: jakub.przybytek
 */

#ifndef INC_ENVSENSORCONFIG_HPP_
#define INC_ENVSENSORCONFIG_HPP_

#include <main.h>

#define SECONDS(x) (x * 1000)
#define MINUTES(x) (x * SECONDS(60))

/*
 * Logger
 */
#define LOGGER_DIRECTORY "env-logs"
#define LOGGER_INTERVAL MINUTES(1)
#define LOGGER_WRITER_BUFFER_SIZE 512
#define LOGGER_READER_BUFFER_SIZE 512

//#define LOGGER_THREAD_RUN_TEST
#define LOGGER_THREAD_INFO
//#define LOGGER_THREAD_TRACE

/*
 * UI Controller
 */
//#define UI_CONTROLLER_INFO
//#define UI_CONTROLLER_TRACE

/*
 * Debug log
 */
//#define DEBUG_LOG_TRACE

/*
 * Display controller
 */
//#define DISPLAY_CONTROLLER_INFO
//#define DISPLAY_CONTROLLER_TRACE

/*
 * Sensors
 */
#define SENSORS_CONTROLLER_BURST_MEASUREMENTS_PERIOD SECONDS(45)
#define SENSORS_CONTROLLER_NORMAL_MEASUREMENTS_PERIOD (MINUTES(15) - BURST_MEASUREMENTS_PERIOD)

//#define SENSORS_CONTROLLER_INFO
//#define SENSORS_CONTROLLER_TRACE

#define PRESSURE_SENSOR_READOUT_DELAY MINUTES(2)

//#define PRESSURE_SENSOR_INFO
//#define PRESSURE_SENSOR_TRACE

#define CO2_SENSOR_READOUT_DELAY_S 3 * 60

//#define CO2_SENSOR_INFO
//#define CO2_SENSOR_TRACE

//#define PARTICLES_SENSOR_INFO
//#define PARTICLES_SENSOR_TRACE

//#define VOLTAGE_SENSOR_INFO
//#define VOLTAGE_SENSOR_TRACE

#define POWER_5V_ENABLE() HAL_GPIO_WritePin(POWER_5V_ENABLE_GPIO_Port, POWER_5V_ENABLE_Pin, GPIO_PIN_SET)
#define POWER_5V_DISABLE() HAL_GPIO_WritePin(POWER_5V_ENABLE_GPIO_Port, POWER_5V_ENABLE_Pin, GPIO_PIN_RESET)

#endif /* INC_ENVSENSORCONFIG_HPP_ */
