#ifndef INC_DISPLAY_EPD_4IN2CONFIG_HPP2_
#define INC_DISPLAY_EPD_4IN2CONFIG_HPP2_

#include <main.h>
#include <Display/Leds.hpp>

#define EPD_RESET_HIGH 			HAL_GPIO_WritePin(E_INK_RESET_GPIO_Port, E_INK_RESET_Pin, GPIO_PIN_SET)
#define EPD_RESET_LOW 			HAL_GPIO_WritePin(E_INK_RESET_GPIO_Port, E_INK_RESET_Pin, GPIO_PIN_RESET)
#define EPD_DATA_COMMAND_HIGH 	HAL_GPIO_WritePin(E_INK_DC_GPIO_Port, E_INK_DC_Pin, GPIO_PIN_SET)
#define EPD_DATA_COMMAND_LOW 	HAL_GPIO_WritePin(E_INK_DC_GPIO_Port, E_INK_DC_Pin, GPIO_PIN_RESET)
#define EPD_CHIP_SELECT_HIGH 	HAL_GPIO_WritePin(E_INK_SELECT_GPIO_Port, E_INK_SELECT_Pin, GPIO_PIN_SET)
#define EPD_CHIP_SELECT_LOW 	HAL_GPIO_WritePin(E_INK_SELECT_GPIO_Port, E_INK_SELECT_Pin, GPIO_PIN_RESET)
#define EPD_BUSY_READ			HAL_GPIO_ReadPin(E_INK_BUSY_GPIO_Port, E_INK_BUSY_Pin)

#define TRACE_TRANSMISSION_START() DISPLAY_LED_On()
#define TRACE_TRANSMISSION_END() DISPLAY_LED_Off()

#endif /* INC_DISPLAY_EPD_4IN2CONFIG_HPP2_ */
